### PR TITLE
Printing Parsing report

### LINKED ISSUE #40: Generate parser report for common commands
## Type of Issue
Add a unit test that generates parser health (with ground truth querying) for common must have commands in : https://docs.google.com/document/d/1lu87-HCqd9NFZo2dryBEv5DtFQyc8dabPxWwgAHC1t0/edit

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

Detailed description of the requested feature/documentation ask/bug report.

## Current Behavior

Description of current behavior or functionality.

## Expected Behavior

Description of the expected behavior or functionality. In case of feature request, please add input and expected output.

## Steps to reproduce

Please add steps to reproduce the bug here along with the stack trace.

## Links to any relevant pastes or documents 

Please post links to any relevant documents that might contain any extra information.

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

### PR DESCRIPTION
**Pull request by kavyasrinet**
# Description

This PR adds a new test that checks the parsing pipeline status for a set of high_priority commands by comparing the expected parses against ground truth files or predictions of semantic parsing model. The PR also logs out parsing model status on these commands but this is more for reporting purpose than testing.

Please note that:
1. This PR adds a set of high-pri must have commands and their expected true logical forms (derived from [here](https://docs.google.com/document/d/1lu87-HCqd9NFZo2dryBEv5DtFQyc8dabPxWwgAHC1t0/edit)) .
2. This PR mimics how dialogue manager goes about getting the logical forms for an input command. i.e. first query ground truth file, if the command is not found query the model.
3. This PR also prints a report of status of parser output against the expected ground truth.

Fixes #40 
This solves the issue of the parsing pipeline failing on the test commands and affecting progress downstream.

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [x] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

This test did not exist before.

# Testing

Screen Shot 2021-02-01 at 4 24 18 PM
Screen Shot 2021-02-01 at 4 24 08 PM

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Comment by anuragprat1k** [comment]
@kavyasrinet This looks great! This should be CI blocking though if we want to ensure using this test that the parsing pipeline never regresses for critical commands, right?

**Comment by kavyasrinet** [comment]
Thanks ! Yes that makes sense. I'll add in an assertion.

**Comment by aszlam** [comment]
would be possible to run the parser even on commands that are in gt, and generate a report about which commands failed to be properly parsed by nsp?   test would still only be blocking if the standard pathway with gt fail, this would just be extra info

**Comment by kavyasrinet** [comment]
Thanks! Yes I can print another table for the model only success and failures on these. So this would then generate two tables: one for overall parsing and one for parser only, would that help ?

**Comment by snyxan** [comment]
related: https://github.com/fairinternal/minecraft/issues/1491

**Comment by anuragprat1k** [comment]
> Thanks! Yes I can print another table for the model only success and failures on these. So this would then generate two tables: one for overall parsing and one for parser only, would that help ?

one table, two columns would be nicer?

**Comment by kavyasrinet** [comment]
> > Thanks! Yes I can print another table for the model only success and failures on these. So this would then generate two tables: one for overall parsing and one for parser only, would that help ?
> 
> one table, two columns would be nicer?

Whops sorry that's what I meant two "columns" not tables.

**Comment by kavyasrinet** [comment]
Pushed in changes for tracking model accuracy. Also updated the PR description with the new screenshots and description

**Review by aszlam — APPROVED** [review]

**Review by anuragprat1k — APPROVED** [review]

**Review by Rebecca-Qian — APPROVED** [review]
This is great, thanks @kavyasrinet for putting this together!

Why is the name of the test file `test_y_parsing`? Can we use a more descriptive name?

**Comment by kavyasrinet** [comment]
> Why is the name of the test file test_y_parsing? Can we use a more descriptive name?
Re the name, I put it so it is run at the end when CI runs the tests otherwise it is hard to read. Let me know if you can think of something better but merging this for now.

**Pull request merged**
