### PR TITLE
[dashboard] enrich the memory2d component

### PR DESCRIPTION
**Pull request by ys1382**
This PR enrich the memory2d component:
 - add the ability to zoom in, zoom out, and draggable
 - add coordinates axes 

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After
image

# Testing

Tested in localhost

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Comment by kavyasrinet** [comment]
Thanks for creating the PR @ys1382. This change is exciting for the dashboard!
For context for the reviewers,  this PR fixes : #439 .
I am good with the PR but will defer to @soumith since he authored the components touched here.

**Review by soumith — APPROVED** [review]
i reviewed it in detail. Thanks so much for making the commits atomic and separate.

It took a bit longer to review than expected because some of the co-ordinate systems weren't obvious to me from the last time I wrote them. I should've left some comments when I did touch this last.
Feel free to leave comments as you touch stuff as well -- around conventions, co-ordinate systems, implementation details that aren't obvious, etc.

**Review by anuragprat1k — APPROVED** [review]
Looks great, thanks for the change!

What's the maximum zoom-in, zoom-out resolution and what happens to the coordinate axes at those resolutions? Wondering if more/less significant digits show up on the axes. Also, backing up @soumith's comment, it would be great if you can add comments while they are still fresh in memory.

**Comment by ys1382** [comment]
> Looks great, thanks for the change!
> 
> What's the maximum zoom-in, zoom-out resolution and what happens to the coordinate axes at those resolutions? Wondering if more/less significant digits show up on the axes. Also, backing up @soumith's comment, it would be great if you can add comments while they are still fresh in memory.

- the maximum zoom-out is 100%, the maximum zoom-in is unlimited
- the number of notches axes is unchanged when zoom-in, zoom-out
- the coordinate point value is shown rounded 2 decimal digits 
  (e.g: 5.123 = 5.12; 5.129 = 5.13)

I added comments: https://github.com/facebookresearch/droidlet/pull/516/commits/93965751b82bef63e35a0b0614f43a9358eaa405

**Review by kavyasrinet — APPROVED** [review]
LGTM with the review comments resolved.

**Pull request merged**
