### PR TITLE
Nsp playground

### PR DESCRIPTION
**Pull request by aszlam**
some modifications of nsp training scripts, especially model saving and loading.

### CODE REVIEW

**Comment by aszlam** [comment]
don't need much of a review except in maybe 
droidlet/perception/semantic_parsing/nsp_transformer_model/query_model.py
droidlet/perception/semantic_parsing/nsp_transformer_model/utils_model.py

**Comment by aszlam** [comment]
adding @anuragprat1k as reviewer bc locobot tests are timing out.  could the nsp model silently failing to load?

**Review by kavyasrinet — APPROVED** [review]
The changes look good to me. I reviewed the `query_model` and `utils_model` files closely.
I'll take a look into what's going on with locobot tests

**Comment by kavyasrinet** [comment]
Okay confirming that this test: https://github.com/facebookresearch/droidlet/blob/main/droidlet/perception/robot/tests/test_perception.py 
doesn't test the nsp model and is failing on CI. I'll just let @anuragprat1k look into what's going on here.

**Comment by anuragprat1k** [comment]
@aszlam @kavyasrinet Posted a fix here https://github.com/facebookresearch/droidlet/pull/665. Feel free to merge the PR into this branch to unblock.

**Pull request merged**
