### PR TITLE
Update fetch and upload models scripts to support versioned models

### PR DESCRIPTION
**Pull request by Rebecca-Qian**
# Description

This PR accomplishes the following
1. Update the model distribution scripts to support versions of models tracked by hash.
2. Update the NSP checksum in the repo, to be in sync with the latest models update.

Changes to data scripts
- rename `tar_and_hash_datasets.sh` to `upload_datasets_to_aws.sh`
- separate file upload script into two: `upload_datasets_to_aws.sh` and `upload_models_to_aws.sh`
- append `/semantic_parser` dir to hash path for models
- some cleanup; send more useful info to stdout

Since this PR also updates the checksum for a model update from earlier today, I'll also include the models changeset:
- Reduced the size of the models tarball from 1.8GB to 660MB.
- Deleted unused backtranslation, old ttad and vision models (backed up to checkpoint)
- Note that I've kept a path to `models/perception` for locobot models download @anuragprat1k 

@anuragprat1k I'll also need you to take a look at the perception models download in `fetch_aws_models.sh`

Fixes # (issue)

#239 

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

Upload:
`./tools/data_scripts/upload_models_to_aws.sh`

Download/health check:
`./tools/data_scripts/try_download.sh`

Version download:
`./tools/data_scripts/fetch_aws_models.sh <agent> <checksum>`

See #226 for specifics of the new distribution protocol.

# Testing

I was working on a stripped down version of the models directory, and tested the models upload with the new framework.

Run output: P290408493

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [x] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Review by anuragprat1k — APPROVED** [review]
Looks good. Please also test the locobot setup using `./try_donwload.sh locobot` - should download models and dataset to the locobot/agent folder.

**Comment by Rebecca-Qian** [comment]
> Looks good. Please also test the locobot setup using `./try_download.sh locobot` - should download models and dataset to the locobot/agent folder.

Verified it downloads to `locobot/agent/models/perception`. Is it safe to remove `craftassist/agent/models/perception`? This was the old path before models were separated

**Comment by anuragprat1k** [comment]
> > Looks good. Please also test the locobot setup using `./try_download.sh locobot` - should download models and dataset to the locobot/agent folder.
> 
> Verified it downloads to `locobot/agent/models/perception`. Is it safe to remove `craftassist/agent/models/perception`? This was the old path before models were separated

From where do you want to remove it?

**Comment by Rebecca-Qian** [comment]
> > > Looks good. Please also test the locobot setup using `./try_download.sh locobot` - should download models and dataset to the locobot/agent folder.
> > 
> > 
> > Verified it downloads to `locobot/agent/models/perception`. Is it safe to remove `craftassist/agent/models/perception`? This was the old path before models were separated
> 
> From where do you want to remove it?

from the models folder in S3

**Pull request merged**
