### PR TITLE
Issues template change

### PR DESCRIPTION
**Pull request by anuragprat1k**
# Description

Proposing that we use github labels for categorizing issues. It is an inbuilt filter on the site. For eg - just clicking on the documentation label pulls up all the documentation issues. We can even add custom labels - like `droidlet hack session` to file away issues for the hack session.

image

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [x] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
fyi, labels can only be tagged by people who have write or triage permissions -- so any one among us on the team

**Review by kavyasrinet — APPROVED** [review]
LGTM

**Review by Rebecca-Qian — APPROVED** [review]
Nice! Request: let's add a high pri label? Can be used in conjunction with other ones.

**Comment by anuragprat1k** [comment]
> fyi, labels can only be tagged by people who have write or triage permissions -- so any one among us on the team

Didn't know that. Won't land this PR then since the text change I made on the issues template here won't make sense for external users. We can just get in the habit of triaging with labels.

**Comment by anuragprat1k** [comment]
> Nice! Request: let's add a high pri label? Can be used in conjunction with other ones.

Yes. Feel free to add labels. Each issue can also have multiple labels.

**Pull request closed without merging**
