### PR TITLE
Unify dashboard

### PR DESCRIPTION
**Pull request by snyxan**
# Description

Unify main dashboard and dashboard in turk by rebasing main branch against turk branch. This PR is huge but I'll ask for reviews for commits that requires one.

This unification (all commits) consists of three kinds:

1.  commits of PRs that are already reviewed and merged into turk branch. I won't ask for reviews because they have already been reviewed.
2. commits which solves import/path error due to the recent refactor & rebasing. These are not reviewed but are pretty mechanical -- just some path renaming work. I won't ask for reviews for those commits.
3. commits aiming at unifying main dashboard and dashboard in turk. (e.g. create new entry point for turk website) and fixing existing issues in dashboard. For those commits I'll ask for reviews by pointing you to the exact commit so that you'll only need to look at a few files at one time.

I'll add more entries to the checklist as soon as previous ones are finished.

## Checklist:

- [ ] Step 1: test if turk version dashboard works as expected after the rebasing.
- [ ] Commit #xxxxx: ask for reviews after Step 1 is finished.

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

### CODE REVIEW

**Comment by snyxan** [comment]
@Rebecca-Qian As first step, could you please help test if turk version dashboard works as expected?

You can visit turk version dashboard via localhost:8000/turk.html. Note that some of the panes might be slight different from the one we were using for turkers (e.g. the mic button is back). This will be addressed later.

**Comment by soumith** [comment]
are all the VoxelWorld additions copied over from some repo? If so, is it possible for you to make it a git submodule or an npm dependency?

**Comment by snyxan** [comment]
Commits to review @soumith :

- [ ] 8d9c60e this adds a new entry point for turk-version dashboard.

**Comment by snyxan** [comment]
@Rebecca-Qian This commit 658134b in `yuxuans/mephisto_dashboard` seems to be lost due to rebasing (the old file has been moved to new path and git failed to resolve it). Could you help check if the changes are reflected in the current branch?

**Comment by soumith** [comment]
reviewed and approved both those commits

**Comment by kavyasrinet** [comment]
They look good to me, too!

**Comment by snyxan** [comment]
High level description of all commits:

1. Most of those commits comes from `yuxuans/mephisto_dashboard` branch, which are already reviewed and merged into that branch while we developed the turk version dashboard.
2. A few new commits are added during unification (and they have new timestamp and shown at the bottom of the commit history). These are either: **conflicts resolution** (path fix, etc., which I'll not request review), or **functional change** (create new entry point for turk version dashboard, etc., which I've requested reviews explicitly)
3. In the `yuxuans/mephisto_dashboard` branch, there're a lot of 'check in yarn build files' commits. These commits are removed during rebasing because it causes lots of trouble. After this PR is approved, I'll run `yarn build` once and check in the latest build files.

**Comment by snyxan** [comment]
> are all the VoxelWorld additions copied over from some repo? If so, is it possible for you to make it a git submodule or an npm dependency?

The code is written by me. The PNGs are copied from another repo (a subset of it) which has [Creative Commons 4.0 Attribution International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) license.

**Comment by soumith** [comment]
Why are these three commits appearing three times?

- Added VoxelJS dashboard renderer
- Added static files
- Added backend changes

**Comment by soumith** [comment]
> The code is written by me. The PNGs are copied from another repo (a subset of it) which has Creative Commons 4.0 Attribution International (CC BY 4.0) license.

In that case, where are we attributing the PNGs? it's not in the main README

**Comment by snyxan** [comment]
> > The code is written by me. The PNGs are copied from another repo (a subset of it) which has Creative Commons 4.0 Attribution International (CC BY 4.0) license.
> 
> In that case, where are we attributing the PNGs? it's not in the main README

Added attribution in d03a86f along with a few copyright header.

**Comment by snyxan** [comment]
> Why are these three commits appearing three times?
> 
> * Added VoxelJS dashboard renderer
> * Added static files
> * Added backend changes

lol it took me a while to figure out what happened here and I found it weird. 

First, I didn't push those three commits three times, I guess it's coming from merging/rebasing.

Then, I took a look at why it can be added three times (because if the content is there, then you cannot add the same content again).  So I took a look at the commit history of `yuxuans/mephisto_dashboard` (this unify branch is based on that one) [here](https://github.com/facebookresearch/droidlet/commits/yuxuans/mephisto_dashboard?before=6cc3c65a1ca14f81a7da5f7a221a83ce5f44cfa9+140&branch=yuxuans%2Fmephisto_dashboard) and find out that in this commit [Log timestamps](https://github.com/facebookresearch/droidlet/commit/e0b5d1bd3406c2ee6da810a4725c234a320b7817), the VoxelWorld stuff just magically disappeared. What that means is in this commit, there's no deletion of VoxelWorld content, and in the previous commit  [change pytorch to 1.4.0](https://github.com/facebookresearch/droidlet/commit/6f40374d7e35e87fa04db2334a0be425301a73f5) the content are still there. 

Finally, even we can see those three commits appear three times, the latest content is correct and VoxelWorld is functioning as expected.

Any ideas? I felt confused too tbh.

**Comment by soumith** [comment]
okay. yea this could be a consequence of / side effects from merge commits -- i.e. `git merge` rather than `git pull --rebase` -- that were done at some point in history.

I don't know if it's worth doing, give it a try and if it looks too hairy, feel free to abort, but one thing to do is to `git pull --rebase origin main` and see how far you get. If things go terrible, you can abort a rebase with `git rebase --abort`

**Review by kavyasrinet — APPROVED** [review]

**Review by Rebecca-Qian — APPROVED** [review]

**Pull request merged**
