### PR TITLE
Set up logging tiers and configure agent log level

### PR DESCRIPTION
**Pull request by Rebecca-Qian**
# Description

Currently almost all log statements are at the `INFO` level. This PR separates informational logging statements into `INFO`, `DEBUG` and higher tiers, and sets the default tier to `INFO`.

Logging tiers:
- `INFO`: High level statements about state changes, events and behavior tracking, eg. client/server init, DB connect, incoming chats, logical form output, bot responses
- `DEBUG`: fine grained info about program execution, eg. function level inputs and outputs
- `WARN`: potentially harmful but non critical failures
- `ERROR`: exception logging and other non-fatal errors eg. JSON validation

If you disagree with how the existing log statements are categorized, feel free to make changes.

PR also adds a `--log_level`/`-log` argument to `argument_parser` to configure log level, eg. 
`python agent/craftassist_agent.py --dev --log_level info`

Fixes # (issue)

#194 

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [x] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

Sample agent log before cleanup:
P250913552 (function calls, controller steps)

Sample startup trace before cleanup:
P250465453 (sys path exposed)

Sample traces after cleanup:
P250921008
P250924857

# Testing

Tested bot in devfair environment.

`python agent/craftassist_agent.py --dev --log_level info`

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Review by anuragprat1k — APPROVED** [review]
Thanks for getting the ball rolling on this! Could you make a post or an issue with your findings on logging as well?

**Comment by snyxan** [comment]
on high level LGTM. I'll give a thorough review when more detail comes in.

**Review by kavyasrinet — APPROVED** [review]
Thanks for creating this PR and taking the first stab at logging.

**Comment by Rebecca-Qian** [comment]
> on high level LGTM. I'll give a thorough review when more detail comes in.

Sure! Here's the follow up PR that creates a NSP logger:
https://github.com/facebookresearch/droidlet/pull/222

**Pull request merged**
