### PR TITLE
Adding location to selectors

### LINKED ISSUE #306: Update location in filters
## Type of Issue

In the grammar, right now we have "filters" -> "location" but "location" really is a selector. Now that we have support for "selector", we should move "location" key to be inside "filters" -> "selector". 

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

### PR DESCRIPTION
**Pull request by kavyasrinet**
# Description

This PR moves locations in filters to be inside `"filters"` -> `"selector"` and fixes #306 

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

`"what is outside the window"`
BEFORE...
```
{'dialogue_type': 'GET_MEMORY',
 'filters': {'location': {'reference_object': {'filters': {'triples': [{'obj_text': [0,
                                                                                     [4,
                                                                                      4]],
                                                                        'pred_text': 'has_name'}]}},
                          'relative_direction': 'OUTSIDE'},
             'memory_type': 'REFERENCE_OBJECT',
             'output': {'attribute': 'NAME'}}}
```

AFTER...
```
{'dialogue_type': 'GET_MEMORY',
 'filters': {'memory_type': 'REFERENCE_OBJECT',
             'output': {'attribute': 'NAME'},
             'selector': {'location': {'reference_object': {'filters': {'triples': [{'obj_text': [0,
                                                                                                  [4,
                                                                                                   4]],
                                                                                     'pred_text': 'has_name'}]}},
                                       'relative_direction': 'OUTSIDE'}}}}
```
Full paste here: https://www.internalfb.com/phabricator/paste/view/P392787589

# Testing

Tested locally

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Comment by kavyasrinet** [comment]
Adding @aszlam to support the interpreter changes and @Rebecca-Qian  to support schema changes

**Review by Rebecca-Qian — CHANGES_REQUESTED** [review]
The `location` spec does not include several keys that we are using in logical forms in the dataset:
- location_type
- triples (are triples even allowed?)
- repeat

Also, `reference_object_1` and `reference_object_2` should be included with the other keys in one place IMO.

**Comment by kavyasrinet** [comment]
I am not sure I understand ?
Can you point me to examples in the dataset with each key you mentioned above ?

**Comment by aszlam** [comment]
interpreter changes are in, tests pass

**Review by aszlam — APPROVED** [review]

**Review by Rebecca-Qian — APPROVED** [review]

**Pull request merged**
