### PR TITLE
Created a turk version of dashboard

### PR DESCRIPTION
**Pull request by snyxan**
# Description

Created a turk version of dashboard:

- dashboard can set url to aws ecr instance ip instead of `localhost` by default.
- removed a bunch of unnecessary components for turk use.
- Merged voxel world branch in.

Now the docker image built in this branch (most recent one) is tagged as latest in aws ecr. In this way, craftassist.io will launch instance based on this branch instead of main.

Which means it's not necessary to merge this PR into main (bc turk version is different than the normal version). The right time to merge it in is when we have something fancier to let people (or us) choose which version they would like to use.

Just need a high level review. If you are reviewing it in detail, please disregard commit `01cfaae`

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [x] I want a deep design review.

## Before

Screen Shot 2021-03-02 at 3 12 04 AM

## After

Screen Shot 2021-03-02 at 2 45 04 AM

# Testing

Tested locally.

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Comment by kavyasrinet** [comment]
Thanks for creating the PR! Since there are 1763 files committed here - can you list the files that need review ?
Also, perhaps not ideal to have all the `png`s in master.

**Comment by Rebecca-Qian** [comment]
Two points of feedback
1. Can you add screenshots to the PR description comparing the dashboard in main and turk version?

2. Do we need all 1.7k files here under version control? We should avoid checking in libraries if possible - that's what `yarn` and `npm` are for. Most of these are `.png` files from what looks like JS libraries.

**Review by Rebecca-Qian — COMMENTED** [review]
Will revisit after the turk specific components are complete.

**Review by Rebecca-Qian — CHANGES_REQUESTED** [review]
It looks like you checked in a build directory `dldashboard/web/build/` - let's not check in autogenerated files

**Comment by snyxan** [comment]
> Thanks for creating the PR! Since there are 1763 files committed here - can you list the files that need review ?
> On a high level - it is not ideal to have all the `png`s in master.

I'll figure out a way to not have all `png`s checked in.

Files need review:
`dldashboard/web/src/MainPane.js`
`dldashboard/web/src/index.js`

**Comment by snyxan** [comment]
> Two points of feedback
> 
> 1. Can you add screenshots to the PR description comparing the dashboard in main and turk version?

Done. Will update when new elements are added.

> 2. Do we need all 1.7k files here under version control? We should avoid checking in libraries if possible - that's what `yarn` and `npm` are for. Most of these are `.png` files from what looks like JS libraries.

This is not JS libraries but I'll figure out a way to not have `png`s checked in before merging into master.

**Comment by snyxan** [comment]
> It looks like you checked in a build directory `dldashboard/web/build/` - let's not check in autogenerated files

It's required to check in this directory when dashboard is modified.

**Comment by kavyasrinet** [comment]
> It looks like you checked in a build directory dldashboard/web/build/ - let's not check in autogenerated files

We should be checking in the build directory files. The dashboard server at port 8000 serves the files in the build directory. But lets check in the build files in a separate PR to make reviewing easy.

**Comment by snyxan** [comment]
This branch has been merged into 'yuxuans/unify_dashboard' branch, which is now merged into main. So close it now.

**Pull request closed without merging**
