### PR TITLE
Fix common req file path issue in ca req file

### PR DESCRIPTION
**Pull request by snyxan**
# Description

After the refactor, the relative path of common requirements.txt in `agent/craftassist/requirements.txt` has changed. It should be '../../requirements.txt' instead of '../requirements.txt'. This PR fixed that issue.

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

**Before**

`pip install -r agents/craftassist/requirements.txt` will throw the following error:

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'agents/craftassist/../requirements.txt'
```

**After**

The above command should work.

# Testing

Tested locally under root dir and passed:

`pip install -r agents/craftassist/requirements.txt`

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
can you make sure this is tested in the CI? why isn't it failing for the Dockerfile for example...

**Comment by snyxan** [comment]
> can you make sure this is tested in the CI? why isn't it failing for the Dockerfile for example...

This `agent/craftassist/requirements.txt` is separated out from the common `requirements.txt` and is not installed in Dockerfile. @kavyasrinet I remembered you separated this one and the locobot req file a long time ago, could you share why we did that (like without `pip install` craftassist-specific requirements it still works just fine. for locobot I'm not sure if installing bot-specific req is a necessity)?

Meanwhile, I can add the code to install this requirements.txt to Dockerfile so that it can be tested.

**Comment by kavyasrinet** [comment]
To answer @soumith 's question it wasn't failing in CI because `agent/craftassist/requirements.txt` really only has one extra dependency `scipy==1.1.0` on top of main `requirements.txt`, and `scipy` is being used in (`craftassist`) code that isn't run in the tests, for example the `voxel_models` folder and parts of `heuristic_perpcetion` that I'm sure aren't being tested. CI was only running the root `requirements.txt` and that sufficed for tests passing. 

I see that locobot and craftassist both have scipy (although different versions), so this can perhaps be moved out to the main file and we can kill  `agent/craftassist/requirements.txt` entirely. I can take another pass at 

>  @kavyasrinet I remembered you separated this one and the locobot req file a long time ago, could you share why we did that ?

Yes we separated out the files into : 
1. common requirements that everyone using droidlet has to install and 
2. agent / environment specific requirements that you only need if you are using the agent (for example we don't need to install `opencv-python` if we aren't using locobot)

**Comment by kavyasrinet** [comment]
What's the status on this @snyxan ? Can we merge this ?

**Pull request merged**
